manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: te9no
      url-base: https://github.com/te9no
    - name: zettaface
      url-base: https://github.com/zettaface
    - name: kot149
      url-base: https://github.com/kot149
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      # remote: zmkfirmware
      remote: te9no
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-analog-input-driver
      remote: badjeff
      revision: main
    - name: zmk-dongle-display
      remote: te9no
      revision: main
    - name: zmk-input-processor-keybind
      remote: zettaface
      # remote: te9no
      revision: main
    - name: cirque-input-module
      remote: petejohanson
      revision: main
    - name: zmk-layout-shift
      remote: kot149
      revision: v1
  self:
    path: config